### ISSUE TITLE
Make mount thicker and use heat insert

### ISSUE THREAD

**Issue by kkardashian** [kejar31/VoronMods#11]
IMO the board mount is so thin, it bends all over the place. Possibly the cables could force the board against the screws creating a short. Would it be possible to make it a few layers thicker? That way it would support the gland better and could also use heat insert for mounting the board instead of the hex nut.

**Comment by kejar31** [comment]
Yes it’s thin but once installed on the spacers and supported by the cable gland mount it is actually pretty strong… there is very little to no chance of it flexing once fully assembled.. Have you fully assembled the mount and attached it to CW2 with the cable gland and the PCB board? If so can you provide pictures of what flex you are talking about?

Also I didn’t want to use the m3 nut either but in order to fit a heated insert I would need to increase the depth of the mount by 2 to 3 mm which would then limit the space between the mount and the rear door by 2 to 3 mm’s

**Comment by kejar31** [comment]
Here I went to my 2.4 that I am working on atm that has the mount installed and tried to flex the mount by pressing down on the pcb… as you can see in the video, the pcb flexes but that mount does nothing 

https://youtube.com/shorts/aoWPJteSKDs?feature=share

again if you have a picture of video of your issue please post it, otherwise I will close this in the next few days

**Comment by kkardashian** [comment]
I tightened the screws as much as I could, it's not too bad indeed. Also the screw head isn't directly underneath pins, so I guess it's okay, I'll cancel this..

**Comment by kkardashian** [comment]
.
